"""domain reliability core

Revision ID: 6ef2908628c0
Revises: 0001_identity
Create Date: 2026-09-22 22:06:28.899224
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6ef2908628c0"
down_revision: str | Sequence[str] | None = "0001_identity"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=60), nullable=False),
        sa.Column("target_id", sa.String(length=80), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.create_table(
        "connectors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("connector_type", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connectors_organization_id"), "connectors", ["organization_id"], unique=False
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("environment", sa.String(length=80), nullable=False),
        sa.Column("service", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployments_deployed_at"), "deployments", ["deployed_at"], unique=False
    )
    op.create_index(
        op.f("ix_deployments_organization_id"), "deployments", ["organization_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("environment", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("trigger_type", sa.String(length=40), nullable=False),
        sa.Column("entity_ref", sa.String(length=255), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incidents_opened_at"), "incidents", ["opened_at"], unique=False)
    op.create_index(
        "ix_incidents_org_status_severity",
        "incidents",
        ["organization_id", "status", "severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incidents_organization_id"), "incidents", ["organization_id"], unique=False
    )
    op.create_table(
        "pipelines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("orchestrator", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_pipelines_org_name"),
    )
    op.create_index(
        op.f("ix_pipelines_organization_id"), "pipelines", ["organization_id"], unique=False
    )
    op.create_table(
        "telemetry_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("environment", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("publish_error", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "event_id", name="uq_telemetry_org_event_id"),
    )
    op.create_index(
        op.f("ix_telemetry_events_event_type"), "telemetry_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_events_occurred_at"), "telemetry_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_events_organization_id"),
        "telemetry_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_telemetry_org_occurred",
        "telemetry_events",
        ["organization_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_runs_incident_id"), "agent_runs", ["incident_id"], unique=False)
    op.create_index(
        op.f("ix_agent_runs_organization_id"), "agent_runs", ["organization_id"], unique=False
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("connector_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug", name="uq_data_sources_org_slug"),
    )
    op.create_index(
        op.f("ix_data_sources_organization_id"), "data_sources", ["organization_id"], unique=False
    )
    op.create_table(
        "incident_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("evidence_type", sa.String(length=40), nullable=False),
        sa.Column("reference_id", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("relevance", sa.Integer(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_evidence_incident_id"), "incident_evidence", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_incident_evidence_organization_id"),
        "incident_evidence",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("pipeline_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_organization_id"), "jobs", ["organization_id"], unique=False)
    op.create_index(op.f("ix_jobs_pipeline_id"), "jobs", ["pipeline_id"], unique=False)
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("external_run_id", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("logs", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "external_run_id", name="uq_pipeline_runs_org_external_id"
        ),
    )
    op.create_index(
        "ix_pipeline_runs_org_started",
        "pipeline_runs",
        ["organization_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_runs_organization_id"), "pipeline_runs", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_runs_pipeline_id"), "pipeline_runs", ["pipeline_id"], unique=False
    )
    op.create_table(
        "remediation_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_remediation_plans_incident_id"), "remediation_plans", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_remediation_plans_organization_id"),
        "remediation_plans",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "agent_tool_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("agent_run_id", sa.UUID(), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_tool_calls_agent_run_id"), "agent_tool_calls", ["agent_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_tool_calls_organization_id"),
        "agent_tool_calls",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("fully_qualified_name", sa.String(length=255), nullable=False),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "fully_qualified_name", name="uq_datasets_org_fqn"),
    )
    op.create_index(
        op.f("ix_datasets_organization_id"), "datasets", ["organization_id"], unique=False
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("logs", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_runs_job_id"), "job_runs", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_job_runs_organization_id"), "job_runs", ["organization_id"], unique=False
    )
    op.create_table(
        "remediation_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("action_type", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("validation_result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["remediation_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_remediation_actions_organization_id"),
        "remediation_actions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_remediation_actions_plan_id"), "remediation_actions", ["plan_id"], unique=False
    )
    op.create_table(
        "data_quality_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("check_type", sa.String(length=32), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_quality_checks_dataset_id"),
        "data_quality_checks",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_checks_organization_id"),
        "data_quality_checks",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "dataset_columns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("data_type", sa.String(length=80), nullable=False),
        sa.Column("nullable", sa.Boolean(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "name", name="uq_dataset_columns_dataset_name"),
    )
    op.create_index(
        op.f("ix_dataset_columns_dataset_id"), "dataset_columns", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_columns_organization_id"),
        "dataset_columns",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "demo_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_demo_records_dataset_id"), "demo_records", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_demo_records_ingested_at"), "demo_records", ["ingested_at"], unique=False
    )
    op.create_index(
        "ix_demo_records_org_dataset_time",
        "demo_records",
        ["organization_id", "dataset_id", "ingested_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_demo_records_organization_id"), "demo_records", ["organization_id"], unique=False
    )
    op.create_table(
        "lineage_edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("source_dataset_id", sa.UUID(), nullable=False),
        sa.Column("target_dataset_id", sa.UUID(), nullable=False),
        sa.Column("edge_type", sa.String(length=40), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "source_dataset_id",
            "target_dataset_id",
            "edge_type",
            name="uq_lineage_edge",
        ),
    )
    op.create_index(
        op.f("ix_lineage_edges_organization_id"), "lineage_edges", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_lineage_edges_source_dataset_id"),
        "lineage_edges",
        ["source_dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lineage_edges_target_dataset_id"),
        "lineage_edges",
        ["target_dataset_id"],
        unique=False,
    )
    op.create_table(
        "schema_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "dataset_id", "version", name="uq_schema_versions_dataset_version"
        ),
    )
    op.create_index(
        op.f("ix_schema_versions_dataset_id"), "schema_versions", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_schema_versions_organization_id"),
        "schema_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "data_quality_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("check_id", sa.UUID(), nullable=False),
        sa.Column("observed_value", sa.JSON(), nullable=False),
        sa.Column("expected_threshold", sa.JSON(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("anomaly", sa.Boolean(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["check_id"], ["data_quality_checks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_quality_results_check_id"), "data_quality_results", ["check_id"], unique=False
    )
    op.create_index(
        op.f("ix_data_quality_results_executed_at"),
        "data_quality_results",
        ["executed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_results_organization_id"),
        "data_quality_results",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_quality_results_org_check_time",
        "data_quality_results",
        ["organization_id", "check_id", "executed_at"],
        unique=False,
    )
    op.create_table(
        "schema_changes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("schema_version_id", sa.UUID(), nullable=False),
        sa.Column("change_type", sa.String(length=32), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("column_name", sa.String(length=160), nullable=False),
        sa.Column("previous_name", sa.String(length=160), nullable=False),
        sa.Column("previous_type", sa.String(length=80), nullable=False),
        sa.Column("current_type", sa.String(length=80), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schema_version_id"], ["schema_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schema_changes_dataset_id"), "schema_changes", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_schema_changes_organization_id"),
        "schema_changes",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schema_changes_schema_version_id"),
        "schema_changes",
        ["schema_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schema_changes_schema_version_id"), table_name="schema_changes")
    op.drop_index(op.f("ix_schema_changes_organization_id"), table_name="schema_changes")
    op.drop_index(op.f("ix_schema_changes_dataset_id"), table_name="schema_changes")
    op.drop_table("schema_changes")
    op.drop_index("ix_quality_results_org_check_time", table_name="data_quality_results")
    op.drop_index(
        op.f("ix_data_quality_results_organization_id"), table_name="data_quality_results"
    )
    op.drop_index(op.f("ix_data_quality_results_executed_at"), table_name="data_quality_results")
    op.drop_index(op.f("ix_data_quality_results_check_id"), table_name="data_quality_results")
    op.drop_table("data_quality_results")
    op.drop_index(op.f("ix_schema_versions_organization_id"), table_name="schema_versions")
    op.drop_index(op.f("ix_schema_versions_dataset_id"), table_name="schema_versions")
    op.drop_table("schema_versions")
    op.drop_index(op.f("ix_lineage_edges_target_dataset_id"), table_name="lineage_edges")
    op.drop_index(op.f("ix_lineage_edges_source_dataset_id"), table_name="lineage_edges")
    op.drop_index(op.f("ix_lineage_edges_organization_id"), table_name="lineage_edges")
    op.drop_table("lineage_edges")
    op.drop_index(op.f("ix_demo_records_organization_id"), table_name="demo_records")
    op.drop_index("ix_demo_records_org_dataset_time", table_name="demo_records")
    op.drop_index(op.f("ix_demo_records_ingested_at"), table_name="demo_records")
    op.drop_index(op.f("ix_demo_records_dataset_id"), table_name="demo_records")
    op.drop_table("demo_records")
    op.drop_index(op.f("ix_dataset_columns_organization_id"), table_name="dataset_columns")
    op.drop_index(op.f("ix_dataset_columns_dataset_id"), table_name="dataset_columns")
    op.drop_table("dataset_columns")
    op.drop_index(op.f("ix_data_quality_checks_organization_id"), table_name="data_quality_checks")
    op.drop_index(op.f("ix_data_quality_checks_dataset_id"), table_name="data_quality_checks")
    op.drop_table("data_quality_checks")
    op.drop_index(op.f("ix_remediation_actions_plan_id"), table_name="remediation_actions")
    op.drop_index(op.f("ix_remediation_actions_organization_id"), table_name="remediation_actions")
    op.drop_table("remediation_actions")
    op.drop_index(op.f("ix_job_runs_organization_id"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_job_id"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index(op.f("ix_datasets_organization_id"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_agent_tool_calls_organization_id"), table_name="agent_tool_calls")
    op.drop_index(op.f("ix_agent_tool_calls_agent_run_id"), table_name="agent_tool_calls")
    op.drop_table("agent_tool_calls")
    op.drop_index(op.f("ix_remediation_plans_organization_id"), table_name="remediation_plans")
    op.drop_index(op.f("ix_remediation_plans_incident_id"), table_name="remediation_plans")
    op.drop_table("remediation_plans")
    op.drop_index(op.f("ix_pipeline_runs_pipeline_id"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_organization_id"), table_name="pipeline_runs")
    op.drop_index("ix_pipeline_runs_org_started", table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index(op.f("ix_jobs_pipeline_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_organization_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_incident_evidence_organization_id"), table_name="incident_evidence")
    op.drop_index(op.f("ix_incident_evidence_incident_id"), table_name="incident_evidence")
    op.drop_table("incident_evidence")
    op.drop_index(op.f("ix_data_sources_organization_id"), table_name="data_sources")
    op.drop_table("data_sources")
    op.drop_index(op.f("ix_agent_runs_organization_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_incident_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_telemetry_org_occurred", table_name="telemetry_events")
    op.drop_index(op.f("ix_telemetry_events_organization_id"), table_name="telemetry_events")
    op.drop_index(op.f("ix_telemetry_events_occurred_at"), table_name="telemetry_events")
    op.drop_index(op.f("ix_telemetry_events_event_type"), table_name="telemetry_events")
    op.drop_table("telemetry_events")
    op.drop_index(op.f("ix_pipelines_organization_id"), table_name="pipelines")
    op.drop_table("pipelines")
    op.drop_index(op.f("ix_incidents_organization_id"), table_name="incidents")
    op.drop_index("ix_incidents_org_status_severity", table_name="incidents")
    op.drop_index(op.f("ix_incidents_opened_at"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_deployments_organization_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_deployed_at"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_connectors_organization_id"), table_name="connectors")
    op.drop_table("connectors")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
